
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloud Resume Challenge Backend

Resources:
  ResumeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CloudResume
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ResumeApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST'"
        AllowHeaders: "'Content-Type,X-Amz-Date'"
        AllowOrigin: "'*'"

  GetResumeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda.lambda_handler
      Runtime: python3.12
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ResumeTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /resume
            Method: GET
            RestApiId: !Ref ResumeApi

  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda.lambda_handler
      Runtime: python3.12
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ResumeTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /visitors
            Method: POST
            RestApiId: !Ref ResumeApi

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ResumeApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

Cors:
  AllowMethods: "'GET,POST,OPTIONS'"
  AllowHeaders: "'Content-Type,X-Amz-Date'"
  AllowOrigin: "'https://resume.yourdomain.com'"
  AllowCredentials: "'true'"