name: Deploy Backend
on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${AWS_ACCOUNT_ID}:role/GitHubActionsRole
        aws-region: ${AWS_REGION}

    - name: Install SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Build SAM Template
      working-directory: ./backend
      run: sam build

    - name: Deploy SAM Stack
      working-directory: ./backend
      run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name CloudResume --capabilities CAPABILITY_IAM